CREATE TABLE IF NOT EXISTS Settings (Character VARCHAR(15) DEFAULT 'MaskDude' PRIMARY KEY, NumberEnemies INT DEFAULT 2, Effects VARCHAR(1) DEFAULT 'y')
CREATE TABLE IF NOT EXISTS Enemies (Animal VARCHAR(10) UNIQUE PRIMARY KEY, damage INT(3))
CREATE TABLE IF NOT EXISTS Traps (Type VARCHAR(10) UNIQUE PRIMARY KEY, damage INT(3))